services:
  web:
    container_name: RUIEapp
    restart: always
    build: ./RUIeServer
    command: gunicorn serverRUI.wsgi:application --bind 0.0.0.0:8000 --reload
    #command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.dev
    links:
      - db
    volumes: 
      - ./static_volume:/src/backendRUIe/static

  db:
    container_name: dbPGruie
    restart: always
    image: postgres:16.4-alpine
    shm_size: 128mb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db

  nginx:
    container_name: RuieNginx
    build: ./nginx
    restart: always
    expose:
      - 80
    links:
      - web
    volumes:
      - ./static_volume:/src/backendRUIe/static
    environment:
      - VIRTUAL_HOST=ruie.dgcor.com, www.ruie.dgcor.com
      - LETSENCRYPT_HOST=ruie.dgcor.com, www.ruie.dgcor.com
      - LETSENCRYPT_EMAIL=dgcor.rui23@gmail.com

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certificados:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certificados:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw