# Generated by Django 4.2.6 on 2026-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_disuadidospunto_alter_usuario_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inadmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('oficina', models.CharField(db_index=True, max_length=50)),
                ('puntoInter', models.CharField(max_length=100)),
                ('nac', models.CharField(db_index=True, max_length=100)),
                ('nombreCompleto', models.CharField(max_length=250)),
                ('nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'No especificado')], db_index=True, default='X', max_length=1)),
                ('edad', models.IntegerField(null=True, verbose_name='Edad')),
            ],
        ),
    ]
