# Generated by Django 4.2.6 on 2025-06-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_msgupdate_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inadmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oficina', models.CharField(max_length=50)),
                ('puntoInter', models.CharField(max_length=100)),
                ('nac', models.CharField(max_length=100)),
                ('hs', models.IntegerField()),
                ('ms', models.IntegerField()),
                ('ha', models.IntegerField()),
                ('ma', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        )
    ]
