# Generated by Django 4.2.6 on 2026-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_inadmitido_msgupdate_info_usuario_str_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatepunto',
            name='fecha',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='oficinaRepre',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rescatepunto',
            name='puntoEstra',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
    ]
