# Generated by Django 4.2.6 on 2026-01-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_msgupdate_info_usuario_str_pass_usuario_tipo_disp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgupdate',
            name='info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='str_pass',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_disp',
            field=models.CharField(choices=[('1', 'Android'), ('2', 'IPhone'), ('3', 'Otro')], default='1', max_length=1),
        ),
    ]
